### ISSUE TITLE
Crashes always for me

### ISSUE THREAD

**Issue by ScottChapman** [hjespers/node-red-contrib-confluent#4]
I create a inbound node, set my REST URL and always takes down my node-red

**Comment by ondicsnc** [comment]
+1

My Log says:

```
19.7.2019 10:42:2819 Jul 10:42:28 - [info] Server now running at http://127.0.0.1:1880/
19.7.2019 10:42:3519 Jul 10:42:35 - [red] Uncaught Exception:
19.7.2019 10:42:3519 Jul 10:42:35 - TypeError: Cannot read property 'subscribe' of undefined
19.7.2019 10:42:35    at /data/node_modules/node-red-contrib-confluent/confluent/confluent.js:35:52
19.7.2019 10:42:35    at Consumers.Consumer.<anonymous> (/data/node_modules/kafka-rest/lib/consumers.js:63:25)
19.7.2019 10:42:35    at IncomingMessage.<anonymous> (/data/node_modules/kafka-rest/lib/client.js:182:13)
19.7.2019 10:42:35    at IncomingMessage.emit (events.js:203:15)
19.7.2019 10:42:35    at endReadableNT (_stream_readable.js:1129:12)
19.7.2019 10:42:35    at process._tickCallback (internal/process/next_tick.js:63:19)
19.7.2019 10:42:35npm ERR! code ELIFECYCLE
19.7.2019 10:42:35npm ERR! errno 1
19.7.2019 10:42:35npm ERR! node-red-docker@1.0.0 start: `node $NODE_OPTIONS node_modules/node-red/red.js -v $FLOWS "--userDir" "/data" "--settings" "/web/scaleit-settings.js"`
19.7.2019 10:42:35npm ERR! Exit status 1
19.7.2019 10:42:35npm ERR!
19.7.2019 10:42:35npm ERR! Failed at the node-red-docker@1.0.0 start script.
19.7.2019 10:42:35npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
19.7.2019 10:42:35
19.7.2019 10:42:35npm ERR! A complete log of this run can be found in:
19.7.2019 10:42:35npm ERR!     /usr/src/node-red/.npm/_logs/2019-07-19T08_42_35_596Z-debug.log
```
