### ISSUE TITLE
Unable to push or get message using confulent

### ISSUE THREAD

**Issue by hinguabhishek** [hjespers/node-red-contrib-confluent#5]
I am getting below error 
[confluent] Error in our kafka input stream
{ Error
    at Object.<anonymous> (/Users/abhishek.y.hingu/.node-red/node_modules/kafka-rest/lib/client.js:201:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/abhishek.y.hingu/.node-red/node_modules/kafka-rest/index.js:18:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
  name: 'APIError',
  status: 500,
  message: 'Internal Server Error',
  data: { error_code: 500, message: 'Internal Server Error' } }

my node-red workflow 
[{"id":"a25f37fe.658048","type":"debug","z":"7d647e6b.eab55","name":"","active":true,"console":"true","complete":"true","x":688,"y":408,"wires":[]},{"id":"910816c7.72b648","type":"confluent out","z":"7d647e6b.eab55","name":"","topic":"testp","key":"","partition":"","proxy":"4295c61d.b1aae8","x":636,"y":331,"wires":[[]]},{"id":"1ac8918b.37d99e","type":"inject","z":"7d647e6b.eab55","name":"","topic":"","payload":"","payloadType":"date","repeat":"1","crontab":"","once":true,"x":472,"y":345,"wires":[["910816c7.72b648"]]},{"id":"42ac37ac.30fea8","type":"confluent in","z":"7d647e6b.eab55","name":"","topic":"testp","cgroup":"node-red-confluent","autocommit":true,"proxy":"4295c61d.b1aae8","x":501,"y":399,"wires":[["a25f37fe.658048"]]},{"id":"4295c61d.b1aae8","type":"rest-proxy","z":"","proxy":"http://localhost:8082","clientid":""}]

**Comment by hinguabhishek** [comment]
If possible please provide one demo example of how to configure this.
